[workspace]
resolver = "2"
members = [
    "crates/computer-model",
    "crates/computer-protocol",
    "crates/computer-runtime",
    "crates/computer-serialization",
    "crates/computer-storage",
]

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "MIT"

[workspace.dependencies]
kdl = "6.7.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
model = { path = "crates/computer-model" }
runtime = { path = "crates/computer-runtime" }
serialization = { path = "crates/computer-serialization" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
