[package]
name = "computer-panel"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
computer-model.workspace = true
dioxus.workspace = true
gloo-net.workspace = true
futures-util.workspace = true
tracing.workspace = true
toml.workspace = true